alias CodeMaria='cd /home/laastar/PowerRangersFuerzaSalvaje && . ./main.sh'
alias ArboldelaVid='export Ratatoskr=$PWD && cd /home/laastar/PowerRangersFuerzaSalvaje && ./Yggdrasill.sh'
alias Thanatos='BahiadeLasMarianas=0 && exit'
alias ChronosSpeakToMe='cd /home/laastar/PowerRangersFuerzaSalvaje && ./Fecha.sh && ./Hora.sh'
alias CanalDelTiempo='cd /home/laastar/PowerRangersFuerzaSalvaje && ./Fecha_Hora.sh'
alias PokedexQuizTime='cd /home/laastar/PowerRangersFuerzaSalvaje && ./pokejuego.sh'
alias RealTimePlayer='cd /home/laastar/PowerRangersFuerzaSalvaje && ./prebeplayer.sh'
alias ElAzarSiempreGana='cd /home/laastar/PowerRangersFuerzaSalvaje && ./Cagliostro.sh'
alias CapitalPunishment='cd /home/laastar/PowerRangersFuerzaSalvaje && ./JuegoAhorcado_base.sh'
alias Manual='sudo man'
