#!/bin/bash

clear

echo -e "\e[37;43;1m  _____________________________________________________________________________________________________________  \e[0m"
echo -e "\e[37;43;1m |  _________________________________________________________________________________________________________  | \e[0m"
echo -e "\e[37;43;1m | |  _____________________________________________________________________________________________________  | | \e[0m"
echo -e "\e[37;43;1m | | |   ________________________________________________________________________________________________  | | | \e[0m"
echo -e "\e[37;43;1m | | |  |                                                                                                | | | | \e[0m"
echo -e "\e[37;43;1m | | |  |                                                                                                | | | | \e[0m"
echo -e "\e[37;43;1m | | |  |                                   \e[97;43;1m BIENVENIDO AL POKEJUEGO\e[37;43;1m                                     | | | | \e[0m"
echo -e "\e[37;43;1m | | |  |                                                                                                | | | | \e[0m"
echo -e "\e[37;43;1m | | |  |________________________________________________________________________________________________| | | | \e[0m"
echo -e "\e[37;43;1m | | |_____________________________________________________________________________________________________| | | \e[0m"
echo -e "\e[37;43;1m | |_________________________________________________________________________________________________________| | \e[0m"
echo -e "\e[37;43;1m |_____________________________________________________________________________________________________________| \e[0m"
echo -e "\e[37;43;1m                                                                                                                 \e[0m"
echo -e "\e[37;43;1m                                                                                                                 \e[0m"
echo -e "\e[37;43;1m                              Este es un juego para verdaderos amantes de Pokémon                                \e[0m"
echo -e "\e[37;43m                            Solo los verdaderos conocedores podrán con este reto!!!                              \e[0m"
echo -e "\e[37;43m                                            Veamos de qué eres capaz                                             \e[0m"
echo -e "\e[37;43m                                                                                                                 \e[0m"
echo -e "\e[37;43m                                      Ingresa tu contraseña para continuar                                       \e[91;49;1m"

read -p "                                               Presiona [Enter]..."

echo -e "\e[90;49m "
sudo apt-get install fortune cowsay
clear


POKE1="Bulbasaur"
POKE2="Ivysaur"
POKE3="Venusaur"
POKE4="Charmander"
POKE5="Charmeleon"
POKE6="Charizard"
POKE7="Squirtle"
POKE8="Wartortle"
POKE9="Blastoise"
POKE10="Caterpie"
POKE11="Metapod"
POKE12="Butterfree"
POKE13="Weedle"
POKE14="Kakuna"
POKE15="Beedrill"
POKE16="Pidgey"
POKE17="Pidgeotto"
POKE18="Pidgeot"
POKE19="Rattata"
POKE20="Raticate"
POKE21="Spearow"
POKE22="Fearow"
POKE23="Ekans"
POKE24="Arbok"
POKE25="Pikachu"
POKE26="Raichu"
POKE27="Sandshrew"
POKE28="Sandslash"
POKE29="Nidoran"
POKE30="Nidorina"

